import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ol className="flex items-center gap-2">
            <li>
              <Link href="/">Page 1</Link>
            </li>
            <li>
              <Link href="/sub">Page 2</Link>
            </li>
          </ol>
        </nav>

        {children}

        <p>Generated at: {new Date().getTime()}</p>
      </body>
    </html>
  );
};

export default RootLayout;

/**
 * Edge Caching
 */

export const dynamic = "force-static";
